apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yaml
images:
  - name: polar-batches-image
    newName: asia-northeast1-docker.pkg.dev/battonaiocr-staging/polar-repo/polar-batches-runner/polar-batches-runner
    newTag: v1.9.0.60b7a16
